// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Hermitage

//@version=4
strategy('STRATEGY', overlay=true, currency=currency.USD, pyramiding=1)
//==============================================================================

origin = 0.0
levelOne = 0.0
wave2Factor = 0.0

var bigNum = pow(10, 7)
var bigNumSqd = bigNum*bigNum
var w2threshold = levelOne - (levelOne - origin) * wave2Factor

f_print(_text) =>
    // Create label on the first bar.
    var _label = label.new(bar_index, na, _text, xloc.bar_index, yloc.price, color(na), label.style_none, color.gray, size.large, text.align_left)
    // On next bars, update the label's x and y position, and the text it displays.
    label.set_xy(_label, bar_index, highest(10)[1])
    label.set_text(_label, _text)

float p_org = na
float p1 = na
float p2 = na
float p3 = na
float p4 = na
float p5 = na
float p_st = na

oneUpOneDnLook () =>
    for i=0 to 999
        j = low
        if floor(j/bigNumSqd) != j/bigNumSqd
            if close[-i] == na
                p_org := sma(close, bigNumSqd + 3)
            else if low[-i] <= origin
                p_org := sma(close, bigNumSqd += 4)


plot(title="org", series=p_org, color=color.teal, display=display.all)
plot(title="one", series=p1, color=color.fuchsia, display=display.all)
plot(title="two", series=p2, color=color.silver, display=display.all)
plot(title="three", series=p3, color=color.yellow, display=display.all)
plot(title="four", series=p4, color=color.red, display=display.all)
plot(title="five", series=p5, color=color.green, display=display.all)
plot(title="st", series=p_st, color=color.gray, display=display.all)

f_print(tostring(bigNumSqd))

